---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[nginx]
      - recipe[dromedary::default]
      - recipe[dromedary::install_dromedary]
    attributes:
      region: us-east-1
      dromedary:
        S3Bucket: dromedary-114930652771
        ArtifactPath: dromedary-20150911-161507.tar.gz
