---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  # - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[nginx]
      - recipe[nodejs]
      - recipe[dromedary::default]
    attributes:
      region: us-east-1
